# 异常：

## 1. 异常：

#### 1. Throwable类

* 作为java异常的顶层父类，有Excecption(异常)和Error(错误)两个子类，catch中捕获的异常只有它和它的子类
* 它的子类Error：不应该试图捕获的严重问题，一般都是jvm运行代码时出现问题，不是代码出现问题
* Exception类：程序运行时出现的错误

#### 2. Exception类：

分两种异常：**非检查性异常（unchecked exception）** 、**检查性异常（checked exception）**

* 第一种 ：在编译时不会发现错误，在运行时会报错：Error 和 RuntimeException 以及他们的子类

  比如空指针异常、数组下标越界等

* 第二种：如SQLException，IOException，ClassNotFoundException，需要对这样的语句做预处理的工作，比如使用try catch finally块或者throws，否则编译不会通过。

#### 3. try catch finally块：

1. try里放可能发生错误的代码，一但try里出现异常，则在 ==try块中==这条语句及后面的语句都会不再执行。

2. 只有在发生异常时，catch块里的代码才会执行。
3. 当try中出现的异常没有被catch捕获，则会先执行finally中的语句，然后在去trycatchfinally外部去匹配异常处理器。
4. try、finally、catch中的局部变量不能共享，而且三者块中间是不能有语句的。
5. 如果catch中也出现了异常，则会先执行finally中的代码，然后在去trycatchfinally外部去匹配异常处理器。
6. 而且异常的父类Exception这个catch只能放在它子类catch的后面，否则编译就会出错
7. 有了这个，即使出错，这几个块后面的语句也会执行。

#### 4. throws/throw：

1. 当try中加入throw new Exception();这条语句时，会主动抛出异常，然后被catch捕获。在try中这条语句后面不能在写其他语句，会出现编译错误。

2. throw必须写在方法中

3. 如果一个方法内部的代码会抛出检查性异常（checked exception），而方法自己又没有对这些异常完全处理掉，则java的编译器会要求你必须在方法的签名上使用 **「throws」** 关键字声明这些可能抛出的异常，否则编译不通过。

   还有几个面试题很恶心：

   ```java
   public static void main(String[] args) {
       int result = test3();
       System.out.println(result);
   }
   
   public static int test3() {
       //try 语句块中有 return 语句时的整体执行顺序
       int i = 1;
       try {
           i++;
           System.out.println("try block, i = " + i);
           return i;
       } catch (Exception e) {
           i++;
           System.out.println("catch block i = " + i);
           return i;
       } finally {
           i = 10;
           System.out.println("finally block i = " + i);
       }
   }
   输出：
   try block, i = 2
   finally block i = 10
   2
   ```

   ```java
   public static int test4() {
       //finally 语句块中有 return 语句
       int i = 1;
       try {
           i++;
           System.out.println("try block, i = " + i);
           return i;
       } catch (Exception e) {
           i++;
           System.out.println("catch block i = " + i);
           return i;
       } finally {
           i++;
           System.out.println("finally block i = " + i);
           return i;
       }
   }
   输出：
   try block, i = 2
   finally block i = 3
   3
   ```

4. 异常详解：https://zhuanlan.zhihu.com/p/353871211
